// GENERATED AUTOMATICALLY. DO NOT EDIT THIS FILE: IT WILL BE OVERWRITTEN.

#include "main.gen.hpp"

/** enum: auto-generated from main.hpp:8: C4_ENUM: TestEnum_e */

template<> const EnumSymbols< TestEnum_e > esyms()
{
    static const EnumSymbols< TestEnum_e >::Sym vals[] = {
        { TE_0, "TE_0"},
        { TE_1, "TE_1"},
        { TE_2, "TE_2"},
    };
    EnumSymbols< TestEnum_e > r(vals);
    return r;
}
/** enum: auto-generated from main.hpp:15: C4_ENUM: TestEnumClass_e */

template<> const EnumSymbols< TestEnumClass_e > esyms()
{
    static const EnumSymbols< TestEnumClass_e >::Sym vals[] = {
        { TestEnumClass_e::TEC_0, "TestEnumClass_e::TEC_0"},
        { TestEnumClass_e::TEC_1, "TestEnumClass_e::TEC_1"},
        { TestEnumClass_e::TEC_2, "TestEnumClass_e::TEC_2"},
        { TestEnumClass_e::TEC_3, "TestEnumClass_e::TEC_3"},
        { TestEnumClass_e::TEC_4, "TestEnumClass_e::TEC_4"},
        { TestEnumClass_e::TEC_5, "TestEnumClass_e::TEC_5"},
        { TestEnumClass_e::TEC_6, "TestEnumClass_e::TEC_6"},
        { TestEnumClass_e::TEC_7, "TestEnumClass_e::TEC_7"},
        { TestEnumClass_e::TEC_8, "TestEnumClass_e::TEC_8"},
    };
    EnumSymbols< TestEnumClass_e > r(vals);
    return r;
}

/** imgui: auto-generated from main.hpp:30: C4_CLASS: TestStruct */

// TestStruct

/** imgui: auto-generated from main.hpp:37: C4_CLASS: TestTpl<T> */

// TestTpl<T>

/** imgui: auto-generated from main.hpp:44: C4_CLASS: TestTpl2<T, U> */

// TestTpl2<T, U>

/** imgui: auto-generated from main.hpp:52: C4_CLASS: TestTpl3<T, U, V> */

// TestTpl3<T, U, V>

/** imgui: auto-generated from main.hpp:61: C4_CLASS: TestTpl4<T, U, V, N> */

// TestTpl4<T, U, V, N>

/** imgui: auto-generated from main.hpp:70: C4_CLASS: TestTpl51<T, U, V, N, AAA> */

// TestTpl51<T, U, V, N, AAA>

/** imgui: auto-generated from main.hpp:80: C4_CLASS: TestTpl52<T, U, V, N, AAA> */

// TestTpl52<T, U, V, N, AAA>

/** imgui: auto-generated from main.hpp:90: C4_CLASS: TestTpl53<T, U, V, N, AAA> */

// TestTpl53<T, U, V, N, AAA>

/** imgui: auto-generated from main.hpp:100: C4_CLASS: TestTpl54<T, U, V, N, AAA> */

// TestTpl54<T, U, V, N, AAA>

/** imgui: auto-generated from main.hpp:110: C4_CLASS: ThisIsATest */

// ThisIsATest
/** enum: auto-generated from main.hpp:113: C4_ENUM: ThisIsATest::TTestEnum_e */

template<> const EnumSymbols< ThisIsATest::TTestEnum_e > esyms()
{
    static const EnumSymbols< ThisIsATest::TTestEnum_e >::Sym vals[] = {
        { ThisIsATest::CE_0, "ThisIsATest::CE_0"},
        { ThisIsATest::CE_1, "ThisIsATest::CE_1"},
        { ThisIsATest::CE_2, "ThisIsATest::CE_2"},
    };
    EnumSymbols< ThisIsATest::TTestEnum_e > r(vals);
    return r;
}